name: slp_parser
version: 0.1.0
homepage: https://github.com/simpleledger/slp-parser.dart
description: Parse Simple Ledger Protocol OP_RETURN data segments with ease!
dependencies:
    convert: ^3.0.0
dev_dependencies:
    test: ^1.14.2
environment:
    sdk: '>=2.12.0 <3.0.0'
